using GlowvitraBilling.Api.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace GlowvitraBilling.Api.Documents;

public class InvoicePdfDocument : IDocument
{
    private readonly Invoice _invoice;
    private readonly SellerProfile _seller;
    private readonly string _customerState;
    private readonly bool _isIntraState;

    public InvoicePdfDocument(Invoice invoice, SellerProfile seller, string customerState, bool isIntraState)
    {
        _invoice = invoice;
        _seller = seller;
        _customerState = customerState;
        _isIntraState = isIntraState;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(30);
            page.DefaultTextStyle(x => x.FontSize(11));

            page.Header().Column(column =>
            {
                column.Item().Text("Glowvitra Billing System").Bold().FontSize(18);
                column.Item().Text($"Invoice: {_invoice.InvoiceNumber}    Date: {_invoice.InvoiceDate:dd/MM/yyyy}");
            });

            page.Content().PaddingVertical(15).Column(column =>
            {
                column.Spacing(10);
                column.Item().Text($"Customer: {_invoice.CustomerName}").SemiBold();
                column.Item().Text($"Phone: {_invoice.CustomerPhone}");
                column.Item().Text($"Address: {_invoice.CustomerAddress}, {_customerState} - {_invoice.Pincode}");
                column.Item().Text($"Seller: {_seller.SellerName}, {_seller.Address}, GSTIN: {_seller.Gstin}");

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(3);
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                        columns.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle).Text("Product");
                        header.Cell().Element(CellStyle).Text("HSN");
                        header.Cell().Element(CellStyle).Text("Qty");
                        header.Cell().Element(CellStyle).AlignRight().Text("Price");
                        header.Cell().Element(CellStyle).AlignRight().Text("Total");
                    });

                    foreach (var item in _invoice.Items)
                    {
                        table.Cell().Element(CellBodyStyle).Text(item.ProductName);
                        table.Cell().Element(CellBodyStyle).Text(item.HsnCode);
                        table.Cell().Element(CellBodyStyle).Text(item.Quantity.ToString());
                        table.Cell().Element(CellBodyStyle).AlignRight().Text(item.BasePrice.ToString("0.00"));
                        table.Cell().Element(CellBodyStyle).AlignRight().Text(item.LineTotal.ToString("0.00"));
                    }
                });

                column.Item().AlignRight().Column(summary =>
                {
                    summary.Item().Text($"Subtotal: ₹ {_invoice.Subtotal:0.00}");
                    if (_isIntraState)
                    {
                        summary.Item().Text($"CGST (9%): ₹ {_invoice.CgstAmount:0.00}");
                        summary.Item().Text($"SGST (9%): ₹ {_invoice.SgstAmount:0.00}");
                    }
                    else
                    {
                        summary.Item().Text($"IGST (18%): ₹ {_invoice.IgstAmount:0.00}");
                    }

                    summary.Item().Text($"Round Off: ₹ {_invoice.RoundOff:0.00}");
                    summary.Item().Text($"Grand Total: ₹ {_invoice.GrandTotal:0.00}").Bold().FontSize(14);
                });
            });

            page.Footer().AlignCenter().Text(x => x.Span("Generated by Glowvitra Billing System"));
        });
    }

    private static IContainer CellStyle(IContainer container) =>
        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten1).Padding(5).Background(Colors.Grey.Lighten3);

    private static IContainer CellBodyStyle(IContainer container) =>
        container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(5);
}
